name: Publish Artifacts
on: push

jobs:
  build:
    name: Publish release artifacts

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: stable
            target: x86_64-unknown-linux-gnu
            use-cross: false
            tar-xz: true
            ext: ''
          - os: ubuntu-latest
            toolchain: stable
            target: x86_64-unknown-linux-musl
            use-cross: true
            tar-xz: true
            ext: ''
          - os: ubuntu-latest
            toolchain: stable
            target: aarch64-unknown-linux-gnu
            use-cross: true
            tar-xz: true
            ext: ''
          - os: ubuntu-latest
            toolchain: stable
            target: aarch64-unknown-linux-musl
            use-cross: true
            tar-xz: true
            ext: ''
          - os: ubuntu-latest
            toolchain: stable
            target: armv7-unknown-linux-gnueabihf
            use-cross: true
            tar-xz: true
            ext: ''
          - os: windows-latest
            toolchain: stable-msvc
            target: x86_64-pc-windows-msvc
            use-cross: false
            tar-xz: false
            ext: '.exe'
          - os: windows-latest
            toolchain: stable
            target: x86_64-pc-windows-gnu
            use-cross: false
            tar-xz: false
            ext: '.exe'
          - os: macos-latest
            toolchain: stable
            target: x86_64-apple-darwin
            use-cross: false
            tar-xz: false
            ext: ''

    runs-on: '${{ matrix.os }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: '${{ matrix.target }}'

      - name: 'Build binary for ${{ matrix.target }}'
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use-cross }}
          command: build
          args: '--all-features --target ${{ matrix.target }}'

      - name: Testing artifact publish
        if: matrix.tar-xz
        run: |-
              mkdir -p 'target/package'
              strip target/${{ matrix.target }}/debug/templar${{ matrix.ext }}
              tar -C '{{ build_dir }}' -cvJf '{{ package_dir }}/{{ bin_name }}-{{ target }}.tar.xz' '{{ bin_name }}'

      - name: Upload artifacts to this build
        uses: actions/upload-artifact@master
        if: matrix.tar-xz
        with:
          name: tar-package
          path: target/packages/
